# Generated by Django 3.2.4 on 2021-10-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emapiapp', '0002_auto_20211031_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='imgUrl',
            field=models.URLField(),
        ),
    ]
